query prometheus_rules($contract: String!) {
  IntentObservabilityContract(name__value: $contract) {
    edges {
      node {
        name {
          value
        }
        intent {
          node {
            name {
              value
            }
            tenant {
              node {
                name {
                  value
                }
              }
            }
          }
        }
        signals {
          edges {
            node {
              name {
                value
              }
              signal {
                value
              }
              direction {
                value
              }
              frequency_seconds {
                value
              }
              severity {
                value
              }
              condition {
                value
              }
              watches {
                node {
                  name {
                    value
                  }
                  ... on IntentRoutingContract {
                    max_prefixes_ipv4 {
                      value
                    }
                    max_prefixes_ipv6 {
                      value
                    }
                    intent {
                      node {
                        tenant {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                    }
                    pe_devices {
                      edges {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
