query prometheus_rules($contract: String!) {
  IntentRoutingContract(name__value: $contract) {
    edges {
      node {
        name {
          value
        }
        max_prefixes_ipv4 {
          value
        }
        max_prefixes_ipv6 {
          value
        }
        tenant {
          node {
            name {
              value
            }
          }
        }
        pe_devices {
          edges {
            node {
              name {
                value
              }
            }
          }
        }
      }
    }
  }
  IntentObservabilitySignal {
    edges {
      node {
        name {
          value
        }
        signal {
          value
        }
        direction {
          value
        }
        frequency_seconds {
          value
        }
        severity {
          value
        }
        condition {
          value
        }
        contract {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}
