query tenant_redundancy {
  IntentReliabilityContract {
    edges {
      node {
        name {
          value
        }
        min_pe_attachments {
          value
        }
        require_distinct_failure_domains {
          value
        }
        policy {
          node {
            intent {
              node {
                tenant {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  IntentReachabilityContract {
    edges {
      node {
        name {
          value
        }
        require_redundancy {
          value
        }
        policy {
          node {
            intent {
              node {
                tenant {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  IntentRoutingContract(role__value: "customer_edge") {
    edges {
      node {
        name {
          value
        }
        policy {
          node {
            intent {
              node {
                tenant {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
            }
          }
        }
        pe_devices {
          edges {
            node {
              name {
                value
              }
              ... on DcimDevice {
                location {
                  node {
                    display_label
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
